
-- pour la lige un


insert into placement_correspondance(plan_id) values ('n3_1-10');
insert into placement_correspondance(plan_id) values ('n3_1-13');
insert into placement_correspondance(plan_id) values ('n3_1-30');
insert into placement_correspondance(plan_id) values ('n3_1-31');
insert into placement_correspondance(plan_id) values ('n3_1-33');
insert into placement_correspondance(plan_id) values ('n3_1-34');
insert into placement_correspondance(plan_id) values ('n3_1-36');
insert into placement_correspondance(plan_id) values ('n3_1-37');
insert into placement_correspondance(plan_id) values ('n3_1-39');
insert into placement_correspondance(plan_id) values ('n3_1-40');
insert into placement_correspondance(plan_id) values ('n3_1-42');
insert into placement_correspondance(plan_id) values ('n3_1-43');
insert into placement_correspondance(plan_id) values ('n3_1-45');
insert into placement_correspondance(plan_id) values ('n3_1-46');

insert into placement_correspondance(plan_id) values ('n3_1-48');
insert into placement_correspondance(plan_id) values ('n3_1-49');

insert into placement_correspondance(plan_id) values ('n3_1-51');
insert into placement_correspondance(plan_id) values ('n3_1-52');

insert into placement_correspondance(plan_id) values ('n3_1-54');
insert into placement_correspondance(plan_id) values ('n3_1-55');

insert into placement_correspondance(plan_id) values ('n3_1-57');
insert into placement_correspondance(plan_id) values ('n3_1-58');

insert into placement_correspondance(plan_id) values ('n3_1-60');
insert into placement_correspondance(plan_id) values ('n3_1-61');

insert into placement_correspondance(plan_id) values ('n3_1-63');
insert into placement_correspondance(plan_id) values ('n3_1-64');

insert into placement_correspondance(plan_id) values ('n3_1-66');
insert into placement_correspondance(plan_id) values ('n3_1-67');

insert into placement_correspondance(plan_id) values ('n3_1-69');
insert into placement_correspondance(plan_id) values ('n3_1-70');




-- Pour la ligne deux
insert into placement_correspondance(plan_id) values ('n3_2-6');
insert into placement_correspondance(plan_id) values ('n3_2-10');
insert into placement_correspondance(plan_id) values ('n3_2-13');
insert into placement_correspondance(plan_id) values ('n3_2-30');
insert into placement_correspondance(plan_id) values ('n3_2-31');
insert into placement_correspondance(plan_id) values ('n3_2-33');
insert into placement_correspondance(plan_id) values ('n3_2-34');
insert into placement_correspondance(plan_id) values ('n3_2-36');
insert into placement_correspondance(plan_id) values ('n3_2-37');
insert into placement_correspondance(plan_id) values ('n3_2-39');
insert into placement_correspondance(plan_id) values ('n3_2-40');
insert into placement_correspondance(plan_id) values ('n3_2-42');
insert into placement_correspondance(plan_id) values ('n3_2-43');
insert into placement_correspondance(plan_id) values ('n3_2-45');
insert into placement_correspondance(plan_id) values ('n3_2-46');
insert into placement_correspondance(plan_id) values ('n3_2-48');
insert into placement_correspondance(plan_id) values ('n3_2-49');
insert into placement_correspondance(plan_id) values ('n3_2-51');
insert into placement_correspondance(plan_id) values ('n3_2-52');
insert into placement_correspondance(plan_id) values ('n3_2-54');
insert into placement_correspondance(plan_id) values ('n3_2-55');
insert into placement_correspondance(plan_id) values ('n3_2-57');
insert into placement_correspondance(plan_id) values ('n3_2-58');
insert into placement_correspondance(plan_id) values ('n3_2-60');
insert into placement_correspondance(plan_id) values ('n3_2-61');
insert into placement_correspondance(plan_id) values ('n3_2-63');
insert into placement_correspondance(plan_id) values ('n3_2-64');
insert into placement_correspondance(plan_id) values ('n3_2-66');
insert into placement_correspondance(plan_id) values ('n3_2-67');
insert into placement_correspondance(plan_id) values ('n3_2-69');
insert into placement_correspondance(plan_id) values ('n3_2-70');

--Pour la troisième ligen
insert into placement_correspondance(plan_id) values ('n3_3-10');
insert into placement_correspondance(plan_id) values ('n3_3-13');
insert into placement_correspondance(plan_id) values ('n3_3-30');
insert into placement_correspondance(plan_id) values ('n3_3-31');
insert into placement_correspondance(plan_id) values ('n3_3-33');
insert into placement_correspondance(plan_id) values ('n3_3-34');
insert into placement_correspondance(plan_id) values ('n3_3-36');
insert into placement_correspondance(plan_id) values ('n3_3-37');
insert into placement_correspondance(plan_id) values ('n3_3-39');
insert into placement_correspondance(plan_id) values ('n3_3-40');
insert into placement_correspondance(plan_id) values ('n3_3-42');
insert into placement_correspondance(plan_id) values ('n3_3-43');
insert into placement_correspondance(plan_id) values ('n3_3-45');
insert into placement_correspondance(plan_id) values ('n3_3-46');
insert into placement_correspondance(plan_id) values ('n3_3-48');
insert into placement_correspondance(plan_id) values ('n3_3-49');
insert into placement_correspondance(plan_id) values ('n3_3-51');
insert into placement_correspondance(plan_id) values ('n3_3-52');
insert into placement_correspondance(plan_id) values ('n3_3-54');
insert into placement_correspondance(plan_id) values ('n3_3-55');
insert into placement_correspondance(plan_id) values ('n3_3-57');
insert into placement_correspondance(plan_id) values ('n3_3-58');
insert into placement_correspondance(plan_id) values ('n3_3-60');
insert into placement_correspondance(plan_id) values ('n3_3-61');
insert into placement_correspondance(plan_id) values ('n3_3-63');
insert into placement_correspondance(plan_id) values ('n3_3-64');
insert into placement_correspondance(plan_id) values ('n3_3-66');
insert into placement_correspondance(plan_id) values ('n3_3-67');
insert into placement_correspondance(plan_id) values ('n3_3-69');
insert into placement_correspondance(plan_id) values ('n3_3-70');

--Pour la quatrieme ligne
insert into placement_correspondance(plan_id) values ('n3_4-30');
insert into placement_correspondance(plan_id) values ('n3_4-31');
insert into placement_correspondance(plan_id) values ('n3_4-33');
insert into placement_correspondance(plan_id) values ('n3_4-34');
insert into placement_correspondance(plan_id) values ('n3_4-36');
insert into placement_correspondance(plan_id) values ('n3_4-37');
insert into placement_correspondance(plan_id) values ('n3_4-39');
insert into placement_correspondance(plan_id) values ('n3_4-40');
insert into placement_correspondance(plan_id) values ('n3_4-42');
insert into placement_correspondance(plan_id) values ('n3_4-43');
insert into placement_correspondance(plan_id) values ('n3_4-45');
insert into placement_correspondance(plan_id) values ('n3_4-46');
insert into placement_correspondance(plan_id) values ('n3_4-48');
insert into placement_correspondance(plan_id) values ('n3_4-49');
insert into placement_correspondance(plan_id) values ('n3_4-51');
insert into placement_correspondance(plan_id) values ('n3_4-52');
insert into placement_correspondance(plan_id) values ('n3_4-54');
insert into placement_correspondance(plan_id) values ('n3_4-55');
insert into placement_correspondance(plan_id) values ('n3_4-57');
insert into placement_correspondance(plan_id) values ('n3_4-58');
insert into placement_correspondance(plan_id) values ('n3_4-60');
insert into placement_correspondance(plan_id) values ('n3_4-61');
insert into placement_correspondance(plan_id) values ('n3_4-63');
insert into placement_correspondance(plan_id) values ('n3_4-64');
insert into placement_correspondance(plan_id) values ('n3_4-66');
insert into placement_correspondance(plan_id) values ('n3_4-67');
insert into placement_correspondance(plan_id) values ('n3_4-69');
insert into placement_correspondance(plan_id) values ('n3_4-70');

--Pour la cinqième ligne
insert into placement_correspondance(plan_id) values ('n3_5-4');
insert into placement_correspondance(plan_id) values ('n3_5-10');
insert into placement_correspondance(plan_id) values ('n3_5-13');
insert into placement_correspondance(plan_id) values ('n3_5-30');
insert into placement_correspondance(plan_id) values ('n3_5-31');
insert into placement_correspondance(plan_id) values ('n3_5-33');
insert into placement_correspondance(plan_id) values ('n3_5-34');
insert into placement_correspondance(plan_id) values ('n3_5-36');
insert into placement_correspondance(plan_id) values ('n3_5-37');
insert into placement_correspondance(plan_id) values ('n3_5-39');
insert into placement_correspondance(plan_id) values ('n3_5-40');
insert into placement_correspondance(plan_id) values ('n3_5-42');
insert into placement_correspondance(plan_id) values ('n3_5-43');
insert into placement_correspondance(plan_id) values ('n3_5-45');
insert into placement_correspondance(plan_id) values ('n3_5-46');
insert into placement_correspondance(plan_id) values ('n3_5-48');
insert into placement_correspondance(plan_id) values ('n3_5-49');
insert into placement_correspondance(plan_id) values ('n3_5-51');
insert into placement_correspondance(plan_id) values ('n3_5-52');
insert into placement_correspondance(plan_id) values ('n3_5-54');
insert into placement_correspondance(plan_id) values ('n3_5-55');
insert into placement_correspondance(plan_id) values ('n3_5-57');
insert into placement_correspondance(plan_id) values ('n3_5-58');
insert into placement_correspondance(plan_id) values ('n3_5-60');
insert into placement_correspondance(plan_id) values ('n3_5-61');
insert into placement_correspondance(plan_id) values ('n3_5-63');
insert into placement_correspondance(plan_id) values ('n3_5-64');
insert into placement_correspondance(plan_id) values ('n3_5-66');
insert into placement_correspondance(plan_id) values ('n3_5-67');
insert into placement_correspondance(plan_id) values ('n3_5-69');
insert into placement_correspondance(plan_id) values ('n3_5-70');

--6em ligne
insert into placement_correspondance(plan_id) values ('n3_6-10');
insert into placement_correspondance(plan_id) values ('n3_6-13');
insert into placement_correspondance(plan_id) values ('n3_6-20');
insert into placement_correspondance(plan_id) values ('n3_6-30');
insert into placement_correspondance(plan_id) values ('n3_6-31');
insert into placement_correspondance(plan_id) values ('n3_6-33');
insert into placement_correspondance(plan_id) values ('n3_6-34');
insert into placement_correspondance(plan_id) values ('n3_6-36');
insert into placement_correspondance(plan_id) values ('n3_6-37');
insert into placement_correspondance(plan_id) values ('n3_6-39');
insert into placement_correspondance(plan_id) values ('n3_6-40');
insert into placement_correspondance(plan_id) values ('n3_6-42');
insert into placement_correspondance(plan_id) values ('n3_6-43');
insert into placement_correspondance(plan_id) values ('n3_6-45');
insert into placement_correspondance(plan_id) values ('n3_6-46');
insert into placement_correspondance(plan_id) values ('n3_6-48');
insert into placement_correspondance(plan_id) values ('n3_6-49');
insert into placement_correspondance(plan_id) values ('n3_6-51');
insert into placement_correspondance(plan_id) values ('n3_6-52');
insert into placement_correspondance(plan_id) values ('n3_6-54');
insert into placement_correspondance(plan_id) values ('n3_6-55');
insert into placement_correspondance(plan_id) values ('n3_6-57');
insert into placement_correspondance(plan_id) values ('n3_6-58');
insert into placement_correspondance(plan_id) values ('n3_6-60');
insert into placement_correspondance(plan_id) values ('n3_6-61');
insert into placement_correspondance(plan_id) values ('n3_6-63');
insert into placement_correspondance(plan_id) values ('n3_6-64');
insert into placement_correspondance(plan_id) values ('n3_6-66');
insert into placement_correspondance(plan_id) values ('n3_6-67');
insert into placement_correspondance(plan_id) values ('n3_6-69');
insert into placement_correspondance(plan_id) values ('n3_6-70');

-- pour la ligne sept
insert into placement_correspondance(plan_id) values ('n3_7-10');
insert into placement_correspondance(plan_id) values ('n3_7-13');


--8em ligne
insert into placement_correspondance(plan_id) values ('n3_8-1 ');

--9em ligne
insert into placement_correspondance(plan_id) values ('n3_9-1 ');
insert into placement_correspondance(plan_id) values ('n3_9-4 ');
insert into placement_correspondance(plan_id) values ('n3_9-6 ');
insert into placement_correspondance(plan_id) values ('n3_9-7 ');
insert into placement_correspondance(plan_id) values ('n3_9-8 ');
insert into placement_correspondance(plan_id) values ('n3_9-9 ');
insert into placement_correspondance(plan_id) values ('n3_9-10');
insert into placement_correspondance(plan_id) values ('n3_9-11');
insert into placement_correspondance(plan_id) values ('n3_9-21');
insert into placement_correspondance(plan_id) values ('n3_9-22');
insert into placement_correspondance(plan_id) values ('n3_9-23');
insert into placement_correspondance(plan_id) values ('n3_9-31');
insert into placement_correspondance(plan_id) values ('n3_9-32');
insert into placement_correspondance(plan_id) values ('n3_9-33');
insert into placement_correspondance(plan_id) values ('n3_9-34');
insert into placement_correspondance(plan_id) values ('n3_9-36');
insert into placement_correspondance(plan_id) values ('n3_9-37');
insert into placement_correspondance(plan_id) values ('n3_9-38');
insert into placement_correspondance(plan_id) values ('n3_9-40');
insert into placement_correspondance(plan_id) values ('n3_9-42');
insert into placement_correspondance(plan_id) values ('n3_9-43');
insert into placement_correspondance(plan_id) values ('n3_9-44');
insert into placement_correspondance(plan_id) values ('n3_9-47');
insert into placement_correspondance(plan_id) values ('n3_9-48');
insert into placement_correspondance(plan_id) values ('n3_9-49');
insert into placement_correspondance(plan_id) values ('n3_9-52');
insert into placement_correspondance(plan_id) values ('n3_9-53');
insert into placement_correspondance(plan_id) values ('n3_9-55');
insert into placement_correspondance(plan_id) values ('n3_9-56');
insert into placement_correspondance(plan_id) values ('n3_9-60');
insert into placement_correspondance(plan_id) values ('n3_9-61');
insert into placement_correspondance(plan_id) values ('n3_9-64');
insert into placement_correspondance(plan_id) values ('n3_9-65');
insert into placement_correspondance(plan_id) values ('n3_9-67');
insert into placement_correspondance(plan_id) values ('n3_9-68');


--10em ligne

insert into placement_correspondance(plan_id) values ('n3_10-4 ');
insert into placement_correspondance(plan_id) values ('n3_10-6 ');
insert into placement_correspondance(plan_id) values ('n3_10-7 ');
insert into placement_correspondance(plan_id) values ('n3_10-8 ');
insert into placement_correspondance(plan_id) values ('n3_10-9 ');
insert into placement_correspondance(plan_id) values ('n3_10-10');
insert into placement_correspondance(plan_id) values ('n3_10-11');

--12em ligne
insert into placement_correspondance(plan_id) values ('n3_12-9 ');
insert into placement_correspondance(plan_id) values ('n3_12-10');
insert into placement_correspondance(plan_id) values ('n3_12-12');
insert into placement_correspondance(plan_id) values ('n3_12-13');
insert into placement_correspondance(plan_id) values ('n3_12-15');
insert into placement_correspondance(plan_id) values ('n3_12-16');
insert into placement_correspondance(plan_id) values ('n3_12-18');
insert into placement_correspondance(plan_id) values ('n3_12-19');
insert into placement_correspondance(plan_id) values ('n3_12-21');
insert into placement_correspondance(plan_id) values ('n3_12-22');
insert into placement_correspondance(plan_id) values ('n3_12-24');
insert into placement_correspondance(plan_id) values ('n3_12-25');
insert into placement_correspondance(plan_id) values ('n3_12-27');
insert into placement_correspondance(plan_id) values ('n3_12-28');
insert into placement_correspondance(plan_id) values ('n3_12-30');
insert into placement_correspondance(plan_id) values ('n3_12-31');
insert into placement_correspondance(plan_id) values ('n3_12-33');
insert into placement_correspondance(plan_id) values ('n3_12-34');
insert into placement_correspondance(plan_id) values ('n3_12-36');
insert into placement_correspondance(plan_id) values ('n3_12-37');
insert into placement_correspondance(plan_id) values ('n3_12-39');
insert into placement_correspondance(plan_id) values ('n3_12-40');
insert into placement_correspondance(plan_id) values ('n3_12-42');
insert into placement_correspondance(plan_id) values ('n3_12-43');
insert into placement_correspondance(plan_id) values ('n3_12-45');
insert into placement_correspondance(plan_id) values ('n3_12-46');
insert into placement_correspondance(plan_id) values ('n3_12-48');
insert into placement_correspondance(plan_id) values ('n3_12-49');
insert into placement_correspondance(plan_id) values ('n3_12-51');
insert into placement_correspondance(plan_id) values ('n3_12-52');
insert into placement_correspondance(plan_id) values ('n3_12-54');
insert into placement_correspondance(plan_id) values ('n3_12-55');
insert into placement_correspondance(plan_id) values ('n3_12-57');
insert into placement_correspondance(plan_id) values ('n3_12-58');
insert into placement_correspondance(plan_id) values ('n3_12-60');
insert into placement_correspondance(plan_id) values ('n3_12-61');
insert into placement_correspondance(plan_id) values ('n3_12-63');
insert into placement_correspondance(plan_id) values ('n3_12-64');
insert into placement_correspondance(plan_id) values ('n3_12-66');
insert into placement_correspondance(plan_id) values ('n3_12-67');
insert into placement_correspondance(plan_id) values ('n3_12-69');
insert into placement_correspondance(plan_id) values ('n3_12-70');



--13em ligne
insert into placement_correspondance(plan_id) values ('n3_13-4 ');
insert into placement_correspondance(plan_id) values ('n3_13-6');
insert into placement_correspondance(plan_id) values ('n3_13-7');
insert into placement_correspondance(plan_id) values ('n3_13-9 ');
insert into placement_correspondance(plan_id) values ('n3_13-10');
insert into placement_correspondance(plan_id) values ('n3_13-12');
insert into placement_correspondance(plan_id) values ('n3_13-13');
insert into placement_correspondance(plan_id) values ('n3_13-15');
insert into placement_correspondance(plan_id) values ('n3_13-16');
insert into placement_correspondance(plan_id) values ('n3_13-18');
insert into placement_correspondance(plan_id) values ('n3_13-19');
insert into placement_correspondance(plan_id) values ('n3_13-21');
insert into placement_correspondance(plan_id) values ('n3_13-22');
insert into placement_correspondance(plan_id) values ('n3_13-24');
insert into placement_correspondance(plan_id) values ('n3_13-25');
insert into placement_correspondance(plan_id) values ('n3_13-27');
insert into placement_correspondance(plan_id) values ('n3_13-28');
insert into placement_correspondance(plan_id) values ('n3_13-30');
insert into placement_correspondance(plan_id) values ('n3_13-31');
insert into placement_correspondance(plan_id) values ('n3_13-33');
insert into placement_correspondance(plan_id) values ('n3_13-34');
insert into placement_correspondance(plan_id) values ('n3_13-36');
insert into placement_correspondance(plan_id) values ('n3_13-37');
insert into placement_correspondance(plan_id) values ('n3_13-39');
insert into placement_correspondance(plan_id) values ('n3_13-40');
insert into placement_correspondance(plan_id) values ('n3_13-42');
insert into placement_correspondance(plan_id) values ('n3_13-43');
insert into placement_correspondance(plan_id) values ('n3_13-45');
insert into placement_correspondance(plan_id) values ('n3_13-46');
insert into placement_correspondance(plan_id) values ('n3_13-48');
insert into placement_correspondance(plan_id) values ('n3_13-49');
insert into placement_correspondance(plan_id) values ('n3_13-51');
insert into placement_correspondance(plan_id) values ('n3_13-52');
insert into placement_correspondance(plan_id) values ('n3_13-54');
insert into placement_correspondance(plan_id) values ('n3_13-55');
insert into placement_correspondance(plan_id) values ('n3_13-57');
insert into placement_correspondance(plan_id) values ('n3_13-58');
insert into placement_correspondance(plan_id) values ('n3_13-60');
insert into placement_correspondance(plan_id) values ('n3_13-61');
insert into placement_correspondance(plan_id) values ('n3_13-63');
insert into placement_correspondance(plan_id) values ('n3_13-64');
insert into placement_correspondance(plan_id) values ('n3_13-66');
insert into placement_correspondance(plan_id) values ('n3_13-67');
insert into placement_correspondance(plan_id) values ('n3_13-69');
insert into placement_correspondance(plan_id) values ('n3_13-70');


--14em ligne
insert into placement_correspondance(plan_id) values ('n3_14-6');
insert into placement_correspondance(plan_id) values ('n3_14-7');
insert into placement_correspondance(plan_id) values ('n3_14-9 ');
insert into placement_correspondance(plan_id) values ('n3_14-10');
insert into placement_correspondance(plan_id) values ('n3_14-12');
insert into placement_correspondance(plan_id) values ('n3_14-13');
insert into placement_correspondance(plan_id) values ('n3_14-15');
insert into placement_correspondance(plan_id) values ('n3_14-16');
insert into placement_correspondance(plan_id) values ('n3_14-18');
insert into placement_correspondance(plan_id) values ('n3_14-19');
insert into placement_correspondance(plan_id) values ('n3_14-21');
insert into placement_correspondance(plan_id) values ('n3_14-22');
insert into placement_correspondance(plan_id) values ('n3_14-24');
insert into placement_correspondance(plan_id) values ('n3_14-25');
insert into placement_correspondance(plan_id) values ('n3_14-27');
insert into placement_correspondance(plan_id) values ('n3_14-28');
insert into placement_correspondance(plan_id) values ('n3_14-30');
insert into placement_correspondance(plan_id) values ('n3_14-31');
insert into placement_correspondance(plan_id) values ('n3_14-33');
insert into placement_correspondance(plan_id) values ('n3_14-34');
insert into placement_correspondance(plan_id) values ('n3_14-36');
insert into placement_correspondance(plan_id) values ('n3_14-37');
insert into placement_correspondance(plan_id) values ('n3_14-39');
insert into placement_correspondance(plan_id) values ('n3_14-40');
insert into placement_correspondance(plan_id) values ('n3_14-42');
insert into placement_correspondance(plan_id) values ('n3_14-43');
insert into placement_correspondance(plan_id) values ('n3_14-45');
insert into placement_correspondance(plan_id) values ('n3_14-46');
insert into placement_correspondance(plan_id) values ('n3_14-48');
insert into placement_correspondance(plan_id) values ('n3_14-49');
insert into placement_correspondance(plan_id) values ('n3_14-51');
insert into placement_correspondance(plan_id) values ('n3_14-52');
insert into placement_correspondance(plan_id) values ('n3_14-54');
insert into placement_correspondance(plan_id) values ('n3_14-55');
insert into placement_correspondance(plan_id) values ('n3_14-57');
insert into placement_correspondance(plan_id) values ('n3_14-58');
insert into placement_correspondance(plan_id) values ('n3_14-60');
insert into placement_correspondance(plan_id) values ('n3_14-61');
insert into placement_correspondance(plan_id) values ('n3_14-63');
insert into placement_correspondance(plan_id) values ('n3_14-64');
insert into placement_correspondance(plan_id) values ('n3_14-66');
insert into placement_correspondance(plan_id) values ('n3_14-67');
insert into placement_correspondance(plan_id) values ('n3_14-69');
insert into placement_correspondance(plan_id) values ('n3_14-70');

--15em ligne
insert into placement_correspondance(plan_id) values ('n3_15-9 ');
insert into placement_correspondance(plan_id) values ('n3_15-10');
insert into placement_correspondance(plan_id) values ('n3_15-12');
insert into placement_correspondance(plan_id) values ('n3_15-13');
insert into placement_correspondance(plan_id) values ('n3_15-15');
insert into placement_correspondance(plan_id) values ('n3_15-16');
insert into placement_correspondance(plan_id) values ('n3_15-18');
insert into placement_correspondance(plan_id) values ('n3_15-19');
insert into placement_correspondance(plan_id) values ('n3_15-21');
insert into placement_correspondance(plan_id) values ('n3_15-22');
insert into placement_correspondance(plan_id) values ('n3_15-24');
insert into placement_correspondance(plan_id) values ('n3_15-25');
insert into placement_correspondance(plan_id) values ('n3_15-27');
insert into placement_correspondance(plan_id) values ('n3_15-28');
insert into placement_correspondance(plan_id) values ('n3_15-30');
insert into placement_correspondance(plan_id) values ('n3_15-31');
insert into placement_correspondance(plan_id) values ('n3_15-33');
insert into placement_correspondance(plan_id) values ('n3_15-34');
insert into placement_correspondance(plan_id) values ('n3_15-36');
insert into placement_correspondance(plan_id) values ('n3_15-37');
insert into placement_correspondance(plan_id) values ('n3_15-39');
insert into placement_correspondance(plan_id) values ('n3_15-40');
insert into placement_correspondance(plan_id) values ('n3_15-42');
insert into placement_correspondance(plan_id) values ('n3_15-43');
insert into placement_correspondance(plan_id) values ('n3_15-45');
insert into placement_correspondance(plan_id) values ('n3_15-46');
insert into placement_correspondance(plan_id) values ('n3_15-48');
insert into placement_correspondance(plan_id) values ('n3_15-49');
insert into placement_correspondance(plan_id) values ('n3_15-51');
insert into placement_correspondance(plan_id) values ('n3_15-52');
insert into placement_correspondance(plan_id) values ('n3_15-54');
insert into placement_correspondance(plan_id) values ('n3_15-55');
insert into placement_correspondance(plan_id) values ('n3_15-57');
insert into placement_correspondance(plan_id) values ('n3_15-58');
insert into placement_correspondance(plan_id) values ('n3_15-60');
insert into placement_correspondance(plan_id) values ('n3_15-61');
insert into placement_correspondance(plan_id) values ('n3_15-63');
insert into placement_correspondance(plan_id) values ('n3_15-64');
insert into placement_correspondance(plan_id) values ('n3_15-66');
insert into placement_correspondance(plan_id) values ('n3_15-67');
insert into placement_correspondance(plan_id) values ('n3_15-69');
insert into placement_correspondance(plan_id) values ('n3_15-70');

--16em ligne
insert into placement_correspondance(plan_id) values ('n3_16-9 ');
insert into placement_correspondance(plan_id) values ('n3_16-10');
insert into placement_correspondance(plan_id) values ('n3_16-12');
insert into placement_correspondance(plan_id) values ('n3_16-13');
insert into placement_correspondance(plan_id) values ('n3_16-15');
insert into placement_correspondance(plan_id) values ('n3_16-16');
insert into placement_correspondance(plan_id) values ('n3_16-18');
insert into placement_correspondance(plan_id) values ('n3_16-19');
insert into placement_correspondance(plan_id) values ('n3_16-21');
insert into placement_correspondance(plan_id) values ('n3_16-22');
insert into placement_correspondance(plan_id) values ('n3_16-24');
insert into placement_correspondance(plan_id) values ('n3_16-25');
insert into placement_correspondance(plan_id) values ('n3_16-27');
insert into placement_correspondance(plan_id) values ('n3_16-28');
insert into placement_correspondance(plan_id) values ('n3_16-30');
insert into placement_correspondance(plan_id) values ('n3_16-31');
insert into placement_correspondance(plan_id) values ('n3_16-33');
insert into placement_correspondance(plan_id) values ('n3_16-34');
insert into placement_correspondance(plan_id) values ('n3_16-36');
insert into placement_correspondance(plan_id) values ('n3_16-37');
insert into placement_correspondance(plan_id) values ('n3_16-39');
insert into placement_correspondance(plan_id) values ('n3_16-40');
insert into placement_correspondance(plan_id) values ('n3_16-42');
insert into placement_correspondance(plan_id) values ('n3_16-43');
insert into placement_correspondance(plan_id) values ('n3_16-45');
insert into placement_correspondance(plan_id) values ('n3_16-46');
insert into placement_correspondance(plan_id) values ('n3_16-48');
insert into placement_correspondance(plan_id) values ('n3_16-49');
insert into placement_correspondance(plan_id) values ('n3_16-51');
insert into placement_correspondance(plan_id) values ('n3_16-52');
insert into placement_correspondance(plan_id) values ('n3_16-54');
insert into placement_correspondance(plan_id) values ('n3_16-55');
insert into placement_correspondance(plan_id) values ('n3_16-57');
insert into placement_correspondance(plan_id) values ('n3_16-58');
insert into placement_correspondance(plan_id) values ('n3_16-60');
insert into placement_correspondance(plan_id) values ('n3_16-61');
insert into placement_correspondance(plan_id) values ('n3_16-63');
insert into placement_correspondance(plan_id) values ('n3_16-64');
insert into placement_correspondance(plan_id) values ('n3_16-66');
insert into placement_correspondance(plan_id) values ('n3_16-67');
insert into placement_correspondance(plan_id) values ('n3_16-69');
insert into placement_correspondance(plan_id) values ('n3_16-70');

--17em ligne
insert into placement_correspondance(plan_id) values ('n3_127-9 ');
insert into placement_correspondance(plan_id) values ('n3_17-10');
insert into placement_correspondance(plan_id) values ('n3_17-12');
insert into placement_correspondance(plan_id) values ('n3_17-13');
insert into placement_correspondance(plan_id) values ('n3_17-15');
insert into placement_correspondance(plan_id) values ('n3_17-16');
insert into placement_correspondance(plan_id) values ('n3_17-18');
insert into placement_correspondance(plan_id) values ('n3_17-19');
insert into placement_correspondance(plan_id) values ('n3_17-21');
insert into placement_correspondance(plan_id) values ('n3_17-22');
insert into placement_correspondance(plan_id) values ('n3_17-24');
insert into placement_correspondance(plan_id) values ('n3_17-25');
insert into placement_correspondance(plan_id) values ('n3_17-27');
insert into placement_correspondance(plan_id) values ('n3_17-28');
insert into placement_correspondance(plan_id) values ('n3_17-30');
insert into placement_correspondance(plan_id) values ('n3_17-31');
insert into placement_correspondance(plan_id) values ('n3_17-33');
insert into placement_correspondance(plan_id) values ('n3_17-34');
insert into placement_correspondance(plan_id) values ('n3_17-36');
insert into placement_correspondance(plan_id) values ('n3_17-37');
insert into placement_correspondance(plan_id) values ('n3_17-39');
insert into placement_correspondance(plan_id) values ('n3_17-40');
insert into placement_correspondance(plan_id) values ('n3_17-42');
insert into placement_correspondance(plan_id) values ('n3_17-43');
insert into placement_correspondance(plan_id) values ('n3_17-45');
insert into placement_correspondance(plan_id) values ('n3_17-46');
insert into placement_correspondance(plan_id) values ('n3_17-48');
insert into placement_correspondance(plan_id) values ('n3_17-49');
insert into placement_correspondance(plan_id) values ('n3_17-51');
insert into placement_correspondance(plan_id) values ('n3_17-52');
insert into placement_correspondance(plan_id) values ('n3_17-54');
insert into placement_correspondance(plan_id) values ('n3_17-55');
insert into placement_correspondance(plan_id) values ('n3_17-57');
insert into placement_correspondance(plan_id) values ('n3_17-58');
insert into placement_correspondance(plan_id) values ('n3_17-60');
insert into placement_correspondance(plan_id) values ('n3_17-61');
insert into placement_correspondance(plan_id) values ('n3_17-63');
insert into placement_correspondance(plan_id) values ('n3_17-64');
insert into placement_correspondance(plan_id) values ('n3_17-66');
insert into placement_correspondance(plan_id) values ('n3_17-67');
insert into placement_correspondance(plan_id) values ('n3_17-69');
insert into placement_correspondance(plan_id) values ('n3_17-70');